services:
  rudi-app:
    build:
      context: ./rudi-app
      args:
        - LOG_LEVEL=DEBUG
  rudi-admin:
    build:
      context: ./rudi-admin
    ports:
      - "8080:8080"
      - "80:80"
      